### ISSUE TITLE
Respecting `confirm` vim setting

### ISSUE THREAD

**Issue by macintacos** [marklcrns/vim-smartq#1]
Right now when I try to close a buffer that has unsaved changes, I see:

```
Changes detected. Please save your file(s)
```

I have [`set confirm`](http://vimdoc.sourceforge.net/htmldoc/options.html#'confirm') which prompts me to save modified files before closing buffers already - any way that this plugin could respect that and let that prompt come through instead?

**Comment by marklcrns** [comment]
Let me know if this works for you.

**Comment by macintacos** [comment]
Works great, thanks!
