### ISSUE TITLE
What did you use to create GIFs?

### ISSUE THREAD

**Issue by Ryuno-Ki** [marklcrns/vim-smartq#2]
Hey there :wave: 

today, I noticed this project via https://twitter.com/VimLinks/status/1407366057539538945
and was wondering what tool you used for creating the demo videos.

Mind sharing?

Thanks in advance!

**Comment by marklcrns** [comment]
Hi!

I used a Windows app [ScreenToGif](https://github.com/NickeManarin/ScreenToGif) for the demo video and [Sauce Code Pro](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro) for the font :)

**Comment by Ryuno-Ki** [comment]
Thank you.

I hoped for a Linux version, but it looks like to be built with .NET (which claims to be cross-platform, but Mono on Linux is usually quite a hassle).
Closing this.
