### ISSUE TITLE
Implement automatic save before quit?

### ISSUE THREAD

**Issue by cands** [marklcrns/vim-smartq#3]
Thanks for making this very handy plugin! It's a great time saver!

I have a feature request. My most common use case is to save the buffer and then quit using "\<Plug\>(smartq_this)".
I wonder if an alternative function could be added so that the buffer is automatically saved before quitting? Maybe could be called "\<Plug\>(smartq_save_this)" or similar.

I guess a mapping similar to "nmap \<silent\> q :up\<CR\>\<bar\>\<Plug\>(smartq_this)" could work, which should save the buffer first if it has been modified. Seems to be working so far but I'm not sure it is suitable in all situations. Anyhow maybe if more users are interested in this type of functionality it could be built into the plugin so it is very easy to setup.

**Comment by marklcrns** [comment]
Hi cands, thanks for taking an interest in the plugin. Never thought of automatic saving before because, personally, I like to have separate mappings for quit and save just so I am aware that its, in fact, saved (I'm OCD like that).  But it seems like a good idea to add this feature into the plugin. I will work on this soon.

**Comment by cands** [comment]
Thanks a lot for looking into it! Yes I imagine habits of how to save differs much among Vim users.

**Comment by marklcrns** [comment]
Just pushed the new  SmartQSave command in the dev branch. Do you mind testing it out before I merge?

**Comment by cands** [comment]
> Just pushed the new SmartQSave command in the dev branch. Do you mind testing it out before I merge?

Excellent, thanks a lot! In my initial tests everything seems to work fine, very handy for my use case. I'll do some further testing a couple of days and let you know if I encounter any issues.

**Comment by cands** [comment]
I have experienced one issue a few times, please see attached screenshot. When this has happened I am not able to save the file using ordinary commands either. However, it occurs rarely and I have not been able to reproduce it. Maybe the screenshot gives you a clue if there is a potential problem with the function. I did not experience this with the mapping "nmap \<silent\> q :up\<CR\>\<bar\>\<Plug\>(smartq_this)".

![20211108_screenshot_selection_vim-smartq](https://user-images.githubusercontent.com/3845017/140739987-b7288d90-b6f9-4e96-b390-8bb472bcaefe.png)

**Comment by marklcrns** [comment]
Similar issue I found with that error involves writting on a terminal https://github.com/vim/vim/issues/2190#issue-263122114. Were you trying to save and quit from a terminal? I added a more general fix that might hopefully cover the error you were referring to in addition to some issues I found along the way.

**Comment by cands** [comment]
No it was not from a terminal, but I think it was from some specialized buffer that was not writable (e.g. help files), sorry I do not remember the details. It has occurred just 2-3 times, it is rare and I have not been able to reproduce it. I'll let you know if I encounter the issue again and if so if I am able to reproduce. Hopefully your new general fix has covered this rare error as well, thank you.

**Comment by marklcrns** [comment]
Will merge dev to master now. The fix seems to be working. Thanks!
